In [1]:
# Загрузите выборку Wine
# https://archive.ics.uci.edu/ml/datasets/Wine
import pandas as pd
data = pd.read_csv('data\wine.data.txt', header=None)
data[:5]

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [2]:
# Извлеките из данных признаки и классы. 
# Класс записан в первом столбце (три варианта), признаки — в столбцах со второго по последний.
classes = data[data.columns[0]]
classes.value_counts()[:5]

2    71
1    59
3    48
Name: 0, dtype: int64

In [3]:
data = data.drop(data.columns[0], 1)
data[:5]

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [4]:
# Во второй части задания необходимо произвести масштабирование признаков
from sklearn import preprocessing
scaled = preprocessing.scale(data)
# И получить масштабированную матрицу, в которой каждый столбец имеет нулевое среднее и единичное стандартное отклонение
scaled[:1]

array([[ 1.51861254, -0.5622498 ,  0.23205254, -1.16959318,  1.91390522,
         0.80899739,  1.03481896, -0.65956311,  1.22488398,  0.25171685,
         0.36217728,  1.84791957,  1.01300893]])

In [5]:
# Выход масштабирования разворачиваем в DataFrame
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(data)[:1]
# StandardScaler делает то же, что и preprocessing.scale (первая строка одинаковая)
# Standardize features by removing the mean and scaling to unit variance

array([[ 1.51861254, -0.5622498 ,  0.23205254, -1.16959318,  1.91390522,
         0.80899739,  1.03481896, -0.65956311,  1.22488398,  0.25171685,
         0.36217728,  1.84791957,  1.01300893]])

In [6]:
print(data[:5])
data[data.columns] = scaler.fit_transform(data[data.columns])
print(data[:5])

      1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735  
         1         2         3         4         5         6         7   \
0  1.518613 -0.562250  0.232053 -1.169593  1.913905  0.808997  1.034819   
1  0.246290 -0.499413 -0.827996 -2.490847  0.018145  0.568648  0.733629   
2  0.196879  0.021231  1.109334 -0.268738  0.088358  0.808997  1.215533   
3  1.691550 -0.346811  0.487926 -0.809251  0.930918  2.491446  1.466525   
4  0.295700  0.227694  1.840403  0.451946  1.281985  0.808997  0.663351   

         8         9      

In [7]:
# Создаем классификатор
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(data, classes)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [8]:
# Создайте генератор разбиений
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, random_state=42, shuffle=True)

for train_index, test_index in kf.split(data):
   print("TRAIN:", train_index[:10], "TEST:", test_index[:10])

TRAIN: [ 0  1  2  3  4  5  6  7  8 10] TEST: [ 9 12 15 16 18 19 24 29 30 31]
TRAIN: [ 0  1  3  5  7  8  9 10 12 13] TEST: [ 2  4  6 11 22 26 27 32 36 38]
TRAIN: [ 1  2  3  4  5  6  7  8  9 11] TEST: [ 0 10 23 25 28 33 39 40 44 47]
TRAIN: [ 0  1  2  4  6  9 10 11 12 14] TEST: [ 3  5  7  8 13 17 34 35 43 46]
TRAIN: [ 0  2  3  4  5  6  7  8  9 10] TEST: [ 1 14 20 21 37 48 50 52 54 57]


In [9]:
from sklearn.model_selection import cross_val_score
cross_val_score(estimator=neigh, X=data, y=classes, cv=kf, scoring='accuracy').mean()

0.94936507936507941

In [10]:
# Найдите точность классификации на кросс-валидации для метода k ближайших соседей при k от 1 до 50
import numpy as np
cv_score = np.zeros(50)

k = 0
while k < 50:
    k += 1
    neigh = KNeighborsClassifier(n_neighbors=k)
    neigh.fit(data, classes)
    kf = KFold(n_splits=5, random_state=42, shuffle=True)
    cv_score[k-1] = cross_val_score(estimator=neigh, X=data, y=classes, cv=kf, scoring='accuracy').mean()
    
cv_score

array([ 0.94396825,  0.93285714,  0.95507937,  0.93825397,  0.94936508,
        0.94952381,  0.94952381,  0.9552381 ,  0.96079365,  0.96079365,
        0.96095238,  0.9552381 ,  0.94952381,  0.96634921,  0.97206349,
        0.97206349,  0.96650794,  0.96650794,  0.95539683,  0.96650794,
        0.96095238,  0.96650794,  0.96095238,  0.9552381 ,  0.9552381 ,
        0.96079365,  0.9552381 ,  0.96634921,  0.97761905,  0.96079365,
        0.9552381 ,  0.96079365,  0.96634921,  0.96634921,  0.96079365,
        0.96079365,  0.9552381 ,  0.96079365,  0.96079365,  0.96079365,
        0.96634921,  0.96079365,  0.96634921,  0.96063492,  0.96634921,
        0.94952381,  0.95507937,  0.94952381,  0.95507937,  0.96063492])

In [11]:
cv_score.argsort()

array([ 1,  3,  0,  4, 12,  5,  6, 47, 45,  2, 46, 48, 36, 30, 26, 23, 24,
        7, 11, 18, 49, 43, 35, 34, 39, 31, 29, 41, 38, 25,  9,  8, 37, 22,
       10, 20, 44, 40, 42, 33, 32, 27, 13, 21, 19, 16, 17, 14, 15, 28], dtype=int32)

In [12]:
# Максимальные индексы
# 0 (k=1) и 34 (k=35)
# 0 - 0.73
# 34 - 0.72
# Ответ 1 = 1
# Ответ 2 = 0.73

In [13]:
# С применением масштабирования
# 28 (k = 29)
# Ответ 3 = 29
# Ответ 4 = 0.98